Exception: Error: [1000] Message: 	No viewport created

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\valer\Documents\flag\Magick-notes\main.py", line 523, in <module>
    dpg.set_viewport_large_icon("Icon/icon.ico")
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\dearpygui\dearpygui.py", line 880, in set_viewport_large_icon
    internal_dpg.configure_viewport(0, large_icon=icon)
SystemError: <built-in function configure_viewport> returned a result with an exception set
